#!/usr/bin/python3
from os import *

indexes = {
	1: "Todolist",
	2: "Bash reference",
	3: "C programming reference",
	4: "Git commands reference",
	5: "Nodejs reference",
	6: "Python programming index",
}

print("What reference text would you like to edit?")
for k,v in indexes.items():
	print(k,v, sep = ') ')
number = int(input("Type number here: "))

dir = "$HOME/"
if (number == 1):
	system("nano -l $HOME/Github/Programmapedia/todolist.txt")
elif(number == 2):
	system("nano -l $HOME/Github/Programmapedia//bashref.txt")
elif(number == 3):
	system("nano -l $HOME/Github/Programmapedia/cref.txt")
elif(number == 4):
	system("nano -l $HOME/Github/Programmapedia/gitref.txt")
elif(number == 5):
	system("nano -l $HOME/Github/Programmapedia/noderef.txt")
elif(number == 6):
	system("nano -l $HOME/Github/Programmapedia//pyIndex.txt")
else:
	print("Invalid input. Try again.")
